// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOpIjEZ8ufiwv8BdZfFDyyhrJvou6hePI',
    appId: '1:754218133868:web:6460ba8aad97931720eb49',
    messagingSenderId: '754218133868',
    projectId: 'back-to-firebase-again',
    authDomain: 'back-to-firebase-again.firebaseapp.com',
    storageBucket: 'back-to-firebase-again.firebasestorage.app',
    measurementId: 'G-HTPMBGNXYM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9Iq1n5yreMgm3zKxYHGxnlpzSBrqMHQg',
    appId: '1:754218133868:android:fefdf55af23d9cd520eb49',
    messagingSenderId: '754218133868',
    projectId: 'back-to-firebase-again',
    storageBucket: 'back-to-firebase-again.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBp5sZIRaewX4VKlYfnZ-zDTUmXeGw6v-U',
    appId: '1:754218133868:ios:80c5d43e7786e55020eb49',
    messagingSenderId: '754218133868',
    projectId: 'back-to-firebase-again',
    storageBucket: 'back-to-firebase-again.firebasestorage.app',
    androidClientId: '754218133868-pu8ngk3j47std4pceshoa9h054u5sev3.apps.googleusercontent.com',
    iosClientId: '754218133868-a6gdmqmp7ganni36cdmgu3fue1qcqs5h.apps.googleusercontent.com',
    iosBundleId: 'com.example.backToFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBp5sZIRaewX4VKlYfnZ-zDTUmXeGw6v-U',
    appId: '1:754218133868:ios:80c5d43e7786e55020eb49',
    messagingSenderId: '754218133868',
    projectId: 'back-to-firebase-again',
    storageBucket: 'back-to-firebase-again.firebasestorage.app',
    androidClientId: '754218133868-pu8ngk3j47std4pceshoa9h054u5sev3.apps.googleusercontent.com',
    iosClientId: '754218133868-a6gdmqmp7ganni36cdmgu3fue1qcqs5h.apps.googleusercontent.com',
    iosBundleId: 'com.example.backToFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCOpIjEZ8ufiwv8BdZfFDyyhrJvou6hePI',
    appId: '1:754218133868:web:135d864e1486931120eb49',
    messagingSenderId: '754218133868',
    projectId: 'back-to-firebase-again',
    authDomain: 'back-to-firebase-again.firebaseapp.com',
    storageBucket: 'back-to-firebase-again.firebasestorage.app',
    measurementId: 'G-K312KL67KT',
  );
}
